version: "3.8"
services:
  mateo2314_mcp_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mateo2314_mcp_server
    networks:
      - main_network
    ports:
      - "127.0.0.1:8090:8090"
    volumes:
      - ./root/main/mcp_server/.env:/app/.env
    env_file:
      - ./root/main/mcp_server/.env
    environment:
      - NODE_ENV=production
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8090
    restart: unless-stopped

networks:
  main_network:
    external: true
    name: main_network
